/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Regions */
        get: operations["list_regions_v1_regions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/regions/by-postcode/{outcode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Region By Postcode */
        get: operations["region_by_postcode_v1_regions_by_postcode__outcode__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/appliances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Appliances */
        get: operations["list_appliances_v1_appliances_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tariffs/agile/{region_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agile Tariff */
        get: operations["agile_tariff_v1_tariffs_agile__region_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/forecast/{region_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Forecast
         * @description The day's carbon (and Agile price) curve for a region — the data the
         *     website's day-band renders. Carbon always resolves (live/typical/sample);
         *     price is present only where Agile is available.
         */
        get: operations["forecast_v1_forecast__region_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/optimise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Optimise Schedule */
        post: operations["optimise_schedule_v1_optimise_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgileTariffOut */
        AgileTariffOut: {
            /** Region */
            region: string;
            /** Product */
            product: string;
            /** Day */
            day: string;
            /** Unit Rates P */
            unit_rates_p: number[];
            /**
             * Source
             * @default live_agile
             */
            source: string;
        };
        /** ApplianceOut */
        ApplianceOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Energy Kwh */
            energy_kwh: number;
            /** Duration Hours */
            duration_hours: number;
            /**
             * Typical Earliest
             * @default
             */
            typical_earliest: string;
            /**
             * Typical Latest
             * @default
             */
            typical_latest: string;
            /**
             * Noise Sensitive
             * @default false
             */
            noise_sensitive: boolean;
        };
        /**
         * ForecastOut
         * @description The day's shape for a region: the 48-slot carbon curve the band draws,
         *     plus the Agile price curve when the region has one. Powers the website's
         *     signature day-band (home hero + results) without running an optimise.
         */
        ForecastOut: {
            /** Price Source */
            price_source?: ("octopus_agile_live" | "user_entered_tariff") | null;
            /** Price Source Label */
            price_source_label?: string | null;
            /**
             * Price Is Live
             * @default false
             */
            price_is_live: boolean;
            /** Price Unavailable Reason */
            price_unavailable_reason?: ("not_supported" | "not_published") | null;
            /**
             * Carbon Source
             * @enum {string}
             */
            carbon_source: "gb_live_forecast" | "ni_eirgrid_typical_profile" | "gb_sample_profile" | "unavailable";
            /** Carbon Source Label */
            carbon_source_label: string;
            /** Retrieved At Utc */
            retrieved_at_utc?: string | null;
            /** Valid From Utc */
            valid_from_utc?: string | null;
            /** Valid To Utc */
            valid_to_utc?: string | null;
            /** Is Live Forecast */
            is_live_forecast: boolean;
            /** Is Fallback */
            is_fallback: boolean;
            /** Fallback Reason */
            fallback_reason?: string | null;
            /** Region */
            region: string;
            /** Region Id */
            region_id: string;
            /** Carbon G */
            carbon_g: number[];
            /** Price P */
            price_p?: number[] | null;
            /** Agile Day */
            agile_day?: string | null;
            /** Agile Product */
            agile_product?: string | null;
            /** Supports Agile */
            supports_agile: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** OptimiseRequest */
        OptimiseRequest: {
            /** Region Id */
            region_id: string;
            tariff: components["schemas"]["TariffSpec"];
            /** Tasks */
            tasks: components["schemas"]["TaskSpec"][];
            /**
             * Objective
             * @default balanced
             * @enum {string}
             */
            objective: "cheapest" | "lowest_carbon" | "balanced" | "avoid_peak";
            /**
             * Cost Weight
             * @default 0.5
             */
            cost_weight: number;
        };
        /** OptimiseResponse */
        OptimiseResponse: {
            /** Price Source */
            price_source?: ("octopus_agile_live" | "user_entered_tariff") | null;
            /** Price Source Label */
            price_source_label?: string | null;
            /**
             * Price Is Live
             * @default false
             */
            price_is_live: boolean;
            /** Price Unavailable Reason */
            price_unavailable_reason?: ("not_supported" | "not_published") | null;
            /**
             * Carbon Source
             * @enum {string}
             */
            carbon_source: "gb_live_forecast" | "ni_eirgrid_typical_profile" | "gb_sample_profile" | "unavailable";
            /** Carbon Source Label */
            carbon_source_label: string;
            /** Retrieved At Utc */
            retrieved_at_utc?: string | null;
            /** Valid From Utc */
            valid_from_utc?: string | null;
            /** Valid To Utc */
            valid_to_utc?: string | null;
            /** Is Live Forecast */
            is_live_forecast: boolean;
            /** Is Fallback */
            is_fallback: boolean;
            /** Fallback Reason */
            fallback_reason?: string | null;
            /** Objective */
            objective: string;
            /** Region */
            region: string;
            /** Total Cost Saving P */
            total_cost_saving_p: number;
            /** Total Carbon Saving G */
            total_carbon_saving_g: number;
            /** Tasks */
            tasks: components["schemas"]["ScheduledTaskOut"][];
            /** Safety Statement */
            safety_statement: string;
        };
        /** RegionOut */
        RegionOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Nation */
            nation: string;
            /** Carbon Source */
            carbon_source: string;
            /** Supports Live Forecast */
            supports_live_forecast: boolean;
            /** Supports Agile */
            supports_agile: boolean;
        };
        /** ScheduledTaskOut */
        ScheduledTaskOut: {
            /** Name */
            name: string;
            /** Device Type */
            device_type: string;
            /** Run Window */
            run_window: string;
            /** Baseline Window */
            baseline_window: string;
            /** Cost Saving P */
            cost_saving_p: number;
            /** Carbon Saving G */
            carbon_saving_g: number;
            /** Robustness Score */
            robustness_score: number;
            /** Robustness Band */
            robustness_band: string;
            /** Caveat */
            caveat: string;
        };
        /** TariffSpec */
        TariffSpec: {
            /**
             * Kind
             * @default flat
             * @enum {string}
             */
            kind: "flat" | "economy7" | "agile" | "manual_half_hourly";
            /**
             * Standing Charge P
             * @default 0
             */
            standing_charge_p: number;
            /** Unit Rate P */
            unit_rate_p?: number | null;
            /** Day Rate P */
            day_rate_p?: number | null;
            /** Night Rate P */
            night_rate_p?: number | null;
            /** Prices P */
            prices_p?: number[] | null;
        };
        /** TaskSpec */
        TaskSpec: {
            /** Name */
            name: string;
            /** Device Type */
            device_type: string;
            /** Energy Kwh */
            energy_kwh: number;
            /** Duration Hours */
            duration_hours: number;
            /**
             * Earliest
             * @default
             */
            earliest: string;
            /**
             * Latest
             * @default
             */
            latest: string;
            /** Preferred */
            preferred?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_regions_v1_regions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionOut"][];
                };
            };
        };
    };
    region_by_postcode_v1_regions_by_postcode__outcode__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                outcode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_appliances_v1_appliances_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplianceOut"][];
                };
            };
        };
    };
    agile_tariff_v1_tariffs_agile__region_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                region_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgileTariffOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forecast_v1_forecast__region_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                region_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    optimise_schedule_v1_optimise_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptimiseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimiseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
